export const ServerErrorResponseEnum = {
  UnprocessableEntity: 'UNPROCESSABLE_ENTITY',
  TokenExpired: 'TOKEN_EXPIRED',
  InvalidateSession: 'INVALIDATE_SESSION',
  Unauthorized: 'UNAUTHORIZED',
  BadRequest: 'BAD_REQUEST',
  Forbidden: 'FORBIDDEN',
  NotFound: 'NOT_FOUND',
  MethodNotAllowed: 'METHOD_NOT_ALLOWED',
  Conflict: 'CONFLICT',
  InternalServerError: 'INTERNAL_SERVER_ERROR',
  BadGateway: 'BAD_GATEWAY',
  ServiceUnavailable: 'SERVICE_UNAVAILABLE',
  GatewayTimeout: 'GATEWAY_TIMEOUT',
  NotificationAlreadyEnabled: 'NOTIFICATION_ALREADY_ENABLED',
  WrongPassword: 'WRONG_PASSWORD',
  UserNotRegistered: 'USER_NOT_REGISTERED',
};
